### ISSUE TITLE
您对环境(starcraft II.py)修改的思路

### ISSUE THREAD

**Issue by zyh1999** [TonghanWang/RODE#10]
您好，我认真的阅读了您发表的rode这篇文章，并尝试复现了您的代码，在复现的过程中发现似乎在您的(starcraft II.py)文件中的init_units函数里加入的对敌人观察的排序，您还特别加上了这段是您写的的注释。当我在原始的https://github.com/oxwhirl/smac/tree/master/smac/env/starcraft2 环境里加上这个初始化排序，发现对效果会有一定的影响。想请问一下您对此处修改的理由？

**Comment by TonghanWang** [comment]
您好，这是因为starcraft这个环境，action和敌人有关（一个attack action针对一个特定敌人），而rode在学action
representation的时候，一个action id必须对应固定的一个action。

这个环境每次reset时，同一个action id可能会攻击不同的敌人，导致action语意变化了，这就没法学好action
representation，所以必须排序。

**Comment by zyh1999** [comment]
谢谢您的回复，想了一下确实是这么回事，难怪我之前尝试复现的时候只加入动作表示不加入角色相关的组件并没有得到比baseline更好的效果(没排序)。另外恳请您也能看一下邮箱里我更详细的问题描述~

**Comment by TonghanWang** [comment]
只加action representation确实应该不咋行，因为action
representation是有语义的，直接用语义空间和策略空间没法对齐.

您的邮件我已仔细阅读并回复😄
