### ISSUE TITLE
issue on performance

### ISSUE THREAD

**Issue by HyunghoNa** [TonghanWang/RODE#9]
Hello, first thank you for sharing your code.
I was especially interested in a role-based MARL approach, and your works and codes were really helpful to me.

By the way, when studying the code your shared, I'm having some trouble to reproduce the performance.
To be specific, unlike the experiments presented in the paper, my result shows much lower performance, even worse than qmix T-T.

I just used the uploaded rode.yaml as it is, and revised the code a little bit at rode-learner.py to limit action spaces based on "role_avail_actions" as the paper did, instead of "avail_actions." 

Maybe there is something that I have missed. 

Is there something that I make sure to check? or should I use different settings ?
(FYI, I tested the code on MMM2 and 6h_vs_8z maps. I run the code in linux env with SC2.4.10 version.)

Here is "rode.yaml" I used 
 --- RODE specific parameters ---

% use epsilon greedy action/role selector
action_selector: "soft_epsilon_greedy"
action_encoder: "obs_reward"
epsilon_start: 1.0
epsilon_finish: 0.05
role_epsilon_finish: 0.05
epsilon_anneal_time: 70000
epsilon_anneal_time_exp: 70000

runner: "episode"

buffer_size: 5000

% update the target network every {} episodes
target_update_interval: 200

% use the Q_Learner to train
agent_output_type: "q"
learner: "rode_learner"
double_q: True
mixer: "qmix"
role_mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "rode"
mac: "rode_mac"
agent: "rode"
role: 'dot'
role_selector: 'dot'
bi_opt: False

n_role_clusters: 5
role_interval: 5
state_latent_dim: 32
action_latent_dim: 20
role_action_spaces_update_start: 50000

% for interpretability
verbose: False # default: False

**Comment by TonghanWang** [comment]
Hi, I guess the problem is how you revised rode-learner.py to limit action spaces.

Could you please provide more details on this?

**Comment by HyunghoNa** [comment]
Thank you for a prompt reply~!

revised parts from the uploaded code are as follows:

@ rode_learner.py

comment line# 68
uncomment line # 69

comment line# 112
uncomment line # 113

comment line# 119
uncomment line # 120

As I mentioned above, the revision is to limit action spaces based on role available actions. 
(To my understand, the paper illustrates that agent's actions are limited based on available action of its role. 
Please correct me if I'm wrong.)

Again, thank you for your help and time !!!

**Comment by TonghanWang** [comment]
Yes, the idea is to limit action spaces, but the limitation is expected to be imposed on exploration (in controllers). Your revised code exerts influence on training. I guess running the original version can reproduce the results. :)

Let me explain why these revisions influence performance. During learning, the role selector is updating, so for a given transition tuple, the role_avail_actions may change. Then, for Q-learning, the maximization of Q values for the next step is also changing. You know, deep Q-learning uses a target network to stablize the targets, but using role_avail_actions makes these targets unstable.

So I think, using role_avail_actions as you do is good, but it renders training unstable in practice. It will be a good question on how to restrict action spaces during training while keep training stable. For now, we only consider limiting action spaces during exploration.

**Comment by HyunghoNa** [comment]
Oh I see~

I appreciate your kind and insightful answer.

Let me try it again with the original version to see if it is a cause of the problem I have, before close this issue.

I'll ask you here, if I have a further question. 
Thank you again!

**Comment by TonghanWang** [comment]
You are welcome :)
